/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-2346e570",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2346e570").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-606064f4",
    path: "/javascript/es6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-606064f4").then(next)
    },
  },
  {
    path: "/javascript/es6/index.html",
    redirect: "/javascript/es6/"
  },
  {
    name: "v-72579036",
    path: "/javascript/utils/regexp.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72579036").then(next)
    },
  },
  {
    name: "v-00ae1b9e",
    path: "/style/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00ae1b9e").then(next)
    },
  },
  {
    path: "/style/css/index.html",
    redirect: "/style/css/"
  },
  {
    name: "v-3312fd57",
    path: "/git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3312fd57").then(next)
    },
  },
  {
    path: "/git/index.html",
    redirect: "/git/"
  },
  {
    name: "v-0fb4b926",
    path: "/javascript/utils/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fb4b926").then(next)
    },
  },
  {
    path: "/javascript/utils/index.html",
    redirect: "/javascript/utils/"
  },
  {
    name: "v-f7372fb4",
    path: "/visual/three/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f7372fb4").then(next)
    },
  },
  {
    path: "/visual/three/index.html",
    redirect: "/visual/three/"
  },
  {
    name: "v-414c6966",
    path: "/nodejs/npm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-414c6966").then(next)
    },
  },
  {
    path: "/nodejs/npm/index.html",
    redirect: "/nodejs/npm/"
  },
  {
    name: "v-4810a1ef",
    path: "/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4810a1ef").then(next)
    },
  },
  {
    path: "/vue/index.html",
    redirect: "/vue/"
  },
  {
    name: "v-5de4348e",
    path: "/interview/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5de4348e").then(next)
    },
  },
  {
    path: "/interview/index.html",
    redirect: "/interview/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]