/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "TanBing的开发笔记",
  "description": "TanBing的开发笔记",
  "base": "/blog/",
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "lang": "zh-CN",
        "heroText": "Notes",
        "heroImage": "/logo.jpeg",
        "tagline": "学习笔记",
        "footer": "MIT Licensed | Copyright © 2019-present TanBing"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2346e570",
      "path": "/",
      "lastUpdated": "2021-6-7 14:32:56"
    },
    {
      "frontmatter": {},
      "regularPath": "/javascript/es6/",
      "relativePath": "javascript/es6/README.md",
      "key": "v-606064f4",
      "path": "/javascript/es6/",
      "lastUpdated": "2021-6-7 14:32:56"
    },
    {
      "title": "常用正则",
      "frontmatter": {},
      "regularPath": "/javascript/utils/regexp.html",
      "relativePath": "javascript/utils/regexp.md",
      "key": "v-72579036",
      "path": "/javascript/utils/regexp.html",
      "headers": [
        {
          "level": 2,
          "title": "验证相关",
          "slug": "验证相关"
        },
        {
          "level": 3,
          "title": "是否是金额（精确到分）",
          "slug": "是否是金额（精确到分）"
        },
        {
          "level": 3,
          "title": "是否是手机号",
          "slug": "是否是手机号"
        },
        {
          "level": 3,
          "title": "是否是邮箱号",
          "slug": "是否是邮箱号"
        },
        {
          "level": 3,
          "title": "是否是 QQ 号",
          "slug": "是否是-qq-号"
        },
        {
          "level": 3,
          "title": "是否是链接地址",
          "slug": "是否是链接地址"
        },
        {
          "level": 3,
          "title": "是否是身份证号码",
          "slug": "是否是身份证号码"
        },
        {
          "level": 2,
          "title": "格式相关",
          "slug": "格式相关"
        },
        {
          "level": 3,
          "title": "344 格式手机号",
          "slug": "_344-格式手机号"
        }
      ],
      "lastUpdated": "2021-6-7 14:32:56"
    },
    {
      "title": "CSS 语法相关",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/style/css/",
      "relativePath": "style/css/README.md",
      "key": "v-00ae1b9e",
      "path": "/style/css/",
      "headers": [
        {
          "level": 2,
          "title": "滚动条样式",
          "slug": "滚动条样式"
        },
        {
          "level": 2,
          "title": "显示省略号",
          "slug": "显示省略号"
        },
        {
          "level": 2,
          "title": "滚动",
          "slug": "滚动"
        },
        {
          "level": 2,
          "title": "CSS 奇淫技巧",
          "slug": "css-奇淫技巧"
        },
        {
          "level": 2,
          "title": "识别 HTML 字符中的 \\n",
          "slug": "识别-html-字符中的-n"
        }
      ],
      "lastUpdated": "2021-6-7 14:32:56"
    },
    {
      "title": "Git",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/git/",
      "relativePath": "git/README.md",
      "key": "v-3312fd57",
      "path": "/git/",
      "headers": [
        {
          "level": 2,
          "title": "常用 Git 命令",
          "slug": "常用-git-命令"
        },
        {
          "level": 2,
          "title": "将代码提交到 github 的 gh-pages 分支",
          "slug": "将代码提交到-github-的-gh-pages-分支"
        },
        {
          "level": 2,
          "title": "删除 Git 中的所有提交历史记录",
          "slug": "删除-git-中的所有提交历史记录"
        },
        {
          "level": 2,
          "title": "1. 新建 git 仓库",
          "slug": "_1-新建-git-仓库"
        },
        {
          "level": 2,
          "title": "2. 配置",
          "slug": "_2-配置"
        },
        {
          "level": 2,
          "title": "3. 向暂存区添加 / 删除文件",
          "slug": "_3-向暂存区添加-删除文件"
        },
        {
          "level": 2,
          "title": "4. 代码提交",
          "slug": "_4-代码提交"
        },
        {
          "level": 2,
          "title": "5. 分支",
          "slug": "_5-分支"
        },
        {
          "level": 2,
          "title": "6. 标签",
          "slug": "_6-标签"
        },
        {
          "level": 2,
          "title": "7. 查看信息",
          "slug": "_7-查看信息"
        },
        {
          "level": 2,
          "title": "8. 提交",
          "slug": "_8-提交"
        },
        {
          "level": 2,
          "title": "9. 撤销",
          "slug": "_9-撤销"
        },
        {
          "level": 2,
          "title": "GIT 拉取远程分支到本地",
          "slug": "git-拉取远程分支到本地"
        }
      ],
      "lastUpdated": "2021-6-7 14:32:56"
    },
    {
      "title": "常用方法",
      "frontmatter": {},
      "regularPath": "/javascript/utils/",
      "relativePath": "javascript/utils/README.md",
      "key": "v-0fb4b926",
      "path": "/javascript/utils/",
      "headers": [
        {
          "level": 2,
          "title": "提取身份证信息",
          "slug": "提取身份证信息"
        },
        {
          "level": 2,
          "title": "滚动到顶部",
          "slug": "滚动到顶部"
        },
        {
          "level": 2,
          "title": "数据类型验证",
          "slug": "数据类型验证"
        },
        {
          "level": 2,
          "title": "深拷贝",
          "slug": "深拷贝"
        },
        {
          "level": 2,
          "title": "获取url中的参数",
          "slug": "获取url中的参数"
        },
        {
          "level": 2,
          "title": "检测设备",
          "slug": "检测设备"
        },
        {
          "level": 2,
          "title": "数组乱序",
          "slug": "数组乱序"
        },
        {
          "level": 2,
          "title": "随机数",
          "slug": "随机数"
        },
        {
          "level": 2,
          "title": "数组去重",
          "slug": "数组去重"
        }
      ],
      "lastUpdated": "2021-6-7 14:32:56"
    },
    {
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/visual/three/",
      "relativePath": "visual/three/README.md",
      "key": "v-f7372fb4",
      "path": "/visual/three/",
      "lastUpdated": "2021-6-7 14:32:56"
    },
    {
      "title": "npm",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/nodejs/npm/",
      "relativePath": "nodejs/npm/README.md",
      "key": "v-414c6966",
      "path": "/nodejs/npm/",
      "headers": [
        {
          "level": 2,
          "title": "脚本命令相关",
          "slug": "脚本命令相关"
        },
        {
          "level": 2,
          "title": "nrm",
          "slug": "nrm"
        },
        {
          "level": 2,
          "title": "npm-check-updates",
          "slug": "npm-check-updates"
        }
      ],
      "lastUpdated": "2021-6-7 14:32:56"
    },
    {
      "title": "Vue",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/vue/",
      "relativePath": "vue/README.md",
      "key": "v-4810a1ef",
      "path": "/vue/",
      "headers": [
        {
          "level": 2,
          "title": "在父组件中监听子组件的生命周期钩子",
          "slug": "在父组件中监听子组件的生命周期钩子"
        },
        {
          "level": 2,
          "title": "截流(throttle)/防抖(debounce)",
          "slug": "截流-throttle-防抖-debounce"
        }
      ],
      "lastUpdated": "2021-6-7 14:32:56"
    },
    {
      "title": "原始类型",
      "frontmatter": {},
      "regularPath": "/interview/",
      "relativePath": "interview/README.md",
      "key": "v-5de4348e",
      "path": "/interview/",
      "headers": [
        {
          "level": 3,
          "title": "原始类型",
          "slug": "原始类型"
        },
        {
          "level": 3,
          "title": "对象类型",
          "slug": "对象类型"
        }
      ]
    }
  ],
  "themeConfig": {
    "repo": "https://github.com/tannnb",
    "repoLabel": "Github",
    "nav": [
      {
        "text": "前端学习",
        "link": "/interview/"
      },
      {
        "text": "学习记录",
        "items": [
          {
            "text": "CSS系列",
            "items": [
              {
                "text": "常用CSS样式",
                "link": "/style/css/"
              }
            ]
          },
          {
            "text": "JavaScript系列",
            "items": [
              {
                "text": "你不知道的JavaScript(上)",
                "link": "/javascript/es6/"
              },
              {
                "text": "常用方法",
                "link": "/javascript/utils/"
              }
            ]
          },
          {
            "text": "可视化系列",
            "items": [
              {
                "text": "three.js",
                "link": "/visual/three/"
              }
            ]
          },
          {
            "text": "Git系列",
            "items": [
              {
                "text": "精通Git",
                "link": "/git/"
              }
            ]
          },
          {
            "text": "nodejs系列",
            "items": [
              {
                "text": "npm配置",
                "link": "/nodejs/npm/"
              }
            ]
          }
        ]
      },
      {
        "text": "播放器",
        "link": "http://music.tannnb.com/"
      }
    ],
    "lastUpdated": "最后更新时间",
    "editLinks": false,
    "editLinkText": "编辑此页",
    "sidebar": "auto",
    "searchMaxSuggestions": 10
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "title": "TanBing的开发笔记",
      "description": "TanBing的开发笔记",
      "path": "/"
    }
  }
}